services:
  laravel-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: laravel-dev
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - /app/vendor
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
    restart: "no"
    networks:
      - laravel-dev

networks:
  laravel-dev:
    driver: bridge
