apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  {{- if .Values.ports }}
  ports:
    {{- range .Values.ports }}
    {{- if eq .serviceName "app" }}
    - port: {{ .port }}
      {{- if eq .identifier "app" }}
      targetPort: 80
      {{- end }}
      name: {{ .identifier }}
    {{- end }}
    {{- end }}
  {{- end }}
  selector:
    app: app