apiVersion: apps/v1
{{- if eq .Values.stage "development"}}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  {{- if eq .Values.stage "development"}}
  serviceName: app
  {{- else }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  {{- end }}
  replicas: {{ ternary 1 0 .Values.enabled }}
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: diploi-pull-secret
      {{- if eq .Values.stage "development"}}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: install-dependencies
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          command: ['composer', 'install', '--optimize-autoloader', '--no-interaction']
          workingDir: /app{{ .Values.folder }}
          volumeMounts:
            - name: app-mount
              mountPath: /app
        - name: migrate-database
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          env:
          - name: DB_HOST
            value: {{ .Values.envMap.DB_HOST.value | default "" | quote }}
          - name: DB_PORT
            value: {{ .Values.envMap.DB_PORT.value | default "" | quote }}
          - name: DB_DATABASE
            value: {{ .Values.envMap.DB_DATABASE.value | default "" | quote }}
          - name: DB_USERNAME
            value: {{ .Values.envMap.DB_USERNAME.value | default "" | quote }}
          - name: DB_PASSWORD
            value: {{ .Values.envMap.DB_PASSWORD.value | default "" | quote }}
          - name: DB_CONNECTION
            value: {{ .Values.envMap.DB_CONNECTION.value | default "" | quote }}
          command:
            - /bin/sh
            - -c
            - |
              echo "Clearing config cache..."
              php artisan config:clear && rm -f bootstrap/cache/config.php

              echo "Running database migrations for ${DB_CONNECTION}..."

              if php artisan migrate --force; then
                echo "✅ Migrations completed successfully"
              else
                echo "❌ Migration FAILED! Check database connection, schema, or .env"
                exit 1
              fi
          workingDir: /app{{ .Values.folder }}
          volumeMounts:
            - name: app-mount
              mountPath: /app
        
        - name: generate-passport-keys
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          command: 
            - /bin/sh
            - -c
            - |
              if [ ! -f storage/oauth-private.key ] || [ ! -f storage/oauth-public.key ]; then
                echo "Generating Laravel Passport keys..."
                php artisan passport:keys --force
              else
                echo "Passport keys already exist, skipping generation."
              fi
          workingDir: /app{{ .Values.folder }}
          volumeMounts:
            - name: app-mount
              mountPath: /app


      {{- end }}
      containers:
        - name: app
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          {{- if eq .Values.stage "development" }}
          workingDir: /app{{ .Values.folder }}/public
          {{- with .Values.containerCommands.developmentStart }}
          command:
            - /bin/sh
            - -c
            - |
          {{ . | nindent 14 }}
          {{- end }}
          {{- else }}
          {{- with .Values.containerCommands.productionStart }}
          command:
            - /bin/sh
            - -c
            - |
          {{ . | nindent 14 }}
          {{- end }}
          {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            - name: APP_PUBLIC_URL
              value: {{ .Values.hosts.app }}
            - name: STAGE
              value: {{ .Values.stage }}
          volumeMounts:
            {{- if hasKey .Values.storage "code" }}
            - name: app-mount
              mountPath: /app
            {{- end }}
      volumes:
        {{- if hasKey .Values.storage "code" }}
        - name: app-mount
          hostPath:
            path: {{ .Values.storage.code.hostPath }}
        {{- end }}
